const enc=new TextEncoder();
const dec=new TextDecoder();

function J(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}})}
function H(body,status=200){return new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8'}})}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function sign(secret,text){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text)))}
async function makeSession(env){const p=b64(enc.encode(JSON.stringify({exp:Date.now()+43200000,n:crypto.randomUUID()})));return p+'.'+b64(await sign(env.SESSION_SECRET,p))}
async function validSession(env,t){try{if(!t||!t.includes('.'))return false;const [p,s]=t.split('.');const key=await crypto.subtle.importKey('raw',enc.encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,unb64(s),enc.encode(p));if(!ok)return false;return JSON.parse(dec.decode(unb64(p))).exp>Date.now()}catch{return false}}
function cookie(req,name){for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return null}
async function admin(req,env){return validSession(env,cookie(req,'bp_session'))}
function eq(a,b){a=String(a??'');b=String(b??'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function frac(s){s=String(s).trim();if(s==='0')return 0;if(s.includes('/')){const[a,b]=s.split('/').map(Number);return b?a/b:0}const n=Number(s);return Number.isFinite(n)?n:0}
function favored(home,away,hdp){const p=String(hdp).split(':').map(x=>x.trim());if(p.length!==2)return{favorite:'Tidak terdeteksi',side:'even',strength:0};const l=frac(p[0]),r=frac(p[1]);if(l===0&&r>0)return{favorite:home,side:'home',strength:r};if(r===0&&l>0)return{favorite:away,side:'away',strength:l};return{favorite:'Seimbang',side:'even',strength:0}}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function score(side,strength){if(side==='home')return pick(strength>=.75?['2-0','2-1','3-0','3-1']:strength>=.5?['1-0','2-0','2-1','3-1']:['1-0','2-1','2-0']);if(side==='away')return pick(strength>=.75?['0-2','1-2','0-3','1-3']:strength>=.5?['0-1','0-2','1-2','1-3']:['0-1','1-2','0-2']);return pick(['0-0','1-1','2-2','1-0','0-1','2-1','1-2'])}
function pred(home,away,hdp){const f=favored(home,away,hdp);let prediction;if(f.side==='home')prediction=home+' WIN';else if(f.side==='away')prediction=away+' WIN';else{const r=Math.random();prediction=r<.4?home+' WIN':r<.8?away+' WIN':'DRAW'}return{favorite:f.favorite,prediction,score:score(f.side,f.strength)}}
function fixture(line,league,year){const rx=/^(\d{1,2})\/(\d{1,2})\s+(\d{1,2}:\d{2})\s+(.+?)\s+VS\s+(.+?)\s+((?:0|\d+\/\d+|\d+(?:\.\d+)?)\s*:\s*(?:0|\d+\/\d+|\d+(?:\.\d+)?))\s*$/i;const m=line.match(rx);if(!m)return null;const day=m[1].padStart(2,'0'),month=m[2].padStart(2,'0'),kick=m[3].length===4?'0'+m[3]:m[3],home=m[4].trim(),away=m[5].trim(),handicap=m[6].replace(/\s+/g,' ').trim(),p=pred(home,away,handicap);return{league,match_date:`${year}-${month}-${day}`,date_display:`${day}/${month}`,kickoff:kick,home,away,handicap,favorite:p.favorite,prediction:p.prediction,score:p.score}}
function parseBulk(raw,year){let league='';const matches=[],errors=[];String(raw||'').replace(/\r/g,'').split('\n').map(x=>x.trim()).forEach((line,i)=>{if(!line)return;const f=fixture(line,league,year);if(f){if(!league)errors.push(`Baris ${i+1}: belum ada heading liga.`);else matches.push(f)}else if(!/\d{1,2}\/\d{1,2}\s+\d{1,2}:\d{2}/.test(line))league=line;else errors.push(`Baris ${i+1} tidak terbaca: ${line}`)});return{matches,errors}}

const PUBLIC=`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jadwal & Prediksi Bola</title><style>
:root{--g:#48ad48;--bg:#eff7ef;--r:#d7231d;--b:#075bd8}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:var(--bg);color:#173519}header{background:linear-gradient(135deg,#2f8438,#58b950);color:#fff;padding:22px 16px}.wrap{max-width:1100px;margin:auto}h1{margin:0}.sub{margin-top:6px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.toolbar>*{padding:10px;border:1px solid #cfe1cf;border-radius:9px;background:#fff}.card{background:#fff;border-radius:14px;overflow:hidden;margin-bottom:16px;box-shadow:0 8px 24px #1f4d2014}.league{background:var(--g);color:#fff;padding:10px 14px;font-weight:800}.tw{overflow:auto}table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:9px 8px;border-bottom:1px solid #e5efe5;font-size:13px;text-align:center}th{background:#e6f4e6}.team{text-align:left!important;font-weight:700}.home{color:var(--r)}.away{color:var(--b)}.pick{color:#1f6d29;font-weight:800}.score{font-weight:900}.empty{background:#fff;padding:28px;border-radius:14px;text-align:center}.admin{color:#fff;font-weight:700}@media(max-width:700px){.toolbar{flex-direction:column}.toolbar>*{width:100%}}
</style></head><body><header><div class="wrap"><h1>⚽ Jadwal & Prediksi Sepak Bola</h1><div class="sub">Update dari Admin Panel • <a class="admin" href="/admin">Admin Login</a></div></div></header><main class="wrap" style="padding:0 16px 24px"><div class="toolbar"><input id="q" placeholder="Cari tim / liga..."><select id="league"><option value="">Semua Liga</option></select><input id="date" type="date"></div><div id="app"></div></main><script>
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let all=[];async function load(){const j=await fetch('/api/matches').then(r=>r.json());all=j.matches||[];render()}function render(){const q=document.getElementById('q').value.toLowerCase(),lf=league.value,df=date.value;const ls=[...new Set(all.map(x=>x.league))].sort(),cur=league.value;league.innerHTML='<option value="">Semua Liga</option>'+ls.map(x=>'<option '+(x===cur?'selected':'')+'>'+E(x)+'</option>').join('');const d=all.filter(x=>(x.league+' '+x.home+' '+x.away+' '+x.prediction).toLowerCase().includes(q)&&(!lf||x.league===lf)&&(!df||x.match_date===df));const g={};d.forEach(x=>(g[x.league]??=[]).push(x));app.innerHTML=d.length?Object.entries(g).map(([l,rs])=>'<section class="card"><div class="league">★ '+E(l)+'</div><div class="tw"><table><thead><tr><th>Tanggal</th><th>Jam</th><th>Pertandingan</th><th>HDP</th><th>Favorit</th><th>Prediksi</th><th>Skor</th></tr></thead><tbody>'+rs.map(x=>'<tr><td>'+E(x.date_display)+'</td><td><b>'+E(x.kickoff)+'</b></td><td class="team"><span class="home">'+E(x.home)+'</span><br><span class="away">'+E(x.away)+'</span></td><td>'+E(x.handicap)+'</td><td>'+E(x.favorite)+'</td><td class="pick">'+E(x.prediction)+'</td><td class="score">'+E(x.score)+'</td></tr>').join('')+'</tbody></table></div></section>').join(''):'<div class="empty">Belum ada pertandingan.</div>'}['q','league','date'].forEach(id=>document.getElementById(id).addEventListener('input',render));load();
</script></body></html>`;

const ADMIN=`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Prediksi Bola</title><style>
:root{--g:#48ad48;--bg:#eff7ef}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:var(--bg);color:#173519}header{background:linear-gradient(135deg,#2f8438,#58b950);color:#fff;padding:18px 16px}.wrap{max-width:1180px;margin:auto}.panel{background:#fff;margin:16px;border-radius:14px;padding:16px;box-shadow:0 8px 24px #1f4d2014}.login{max-width:420px;margin:70px auto}.hidden{display:none!important}input,textarea,button{font:inherit}input,textarea{width:100%;padding:10px;border:1px solid #cadfca;border-radius:8px}textarea{min-height:280px;font-family:Consolas,monospace;line-height:1.55}button{border:0;border-radius:9px;padding:10px 14px;font-weight:700;cursor:pointer}.btn{background:var(--g);color:white}.btn2{background:#edf4ed}.danger{background:#fff0ef;color:#a5221b}.top{display:flex;justify-content:space-between;gap:10px;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.note{background:#fff8d8;border:1px solid #ecd774;padding:10px;border-radius:9px;margin:12px 0}.tw{overflow:auto;border:1px solid #dce9dc;border-radius:10px;margin-top:12px}table{width:100%;border-collapse:collapse;min-width:900px}th,td{padding:8px;border-bottom:1px solid #e7efe7;font-size:12px;text-align:left}th{background:#e6f4e6}.pick{font-weight:800;color:#1f6d29}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}a{color:inherit}@media(max-width:700px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><header><div class="wrap top"><div><h1 style="margin:0">⚽ Admin Prediksi Bola</h1><div style="font-size:12px">Paste jadwal, proses, publish semua.</div></div><a href="/">← Lihat Website</a></div></header><div id="loginBox" class="panel login"><h2>Admin Login</h2><label>Username</label><input id="user"><label style="display:block;margin-top:10px">Password</label><input id="pass" type="password"><button class="btn" style="margin-top:12px" onclick="login()">LOGIN</button><div id="loginMsg" style="color:#b22;margin-top:8px"></div></div><main id="app" class="wrap hidden"><section class="panel"><div class="top"><div><h2 style="margin:0">Paste Jadwal</h2><div style="font-size:12px;color:#687">Heading liga dan pertandingan dibaca otomatis.</div></div><button class="btn2" onclick="logout()">Logout</button></div><div class="grid" style="margin-top:14px"><div><label>Tahun</label><input id="year" type="number" value="2026"></div><div><label>Mode</label><input value="Favorit handicap + skor acak" disabled></div></div><div class="note">0 : 1/2 = home favorit. 1/4 : 0 = away favorit. 0 : 0 = seimbang.</div><textarea id="bulk">ITALY SERIE A\n\n08/09 0:00  Cagliari  VS  Lecce 0 : 1/2\n08/09 2:45  Udinese  VS  Lazio 0 : 1/4\n\nSPAIN LA LIGA\n\n08/09 1:00  Getafe CF  VS  Celta Vigo 0 : 1/4\n08/09 3:30  Elche  VS  Real Sociedad 1/4 : 0\n\nSWEDEN ALLSVENSKAN\n\n08/09 1:00  Mjallby  VS  IFK Goteborg 0 : 1/4\n08/09 1:00  Kalmar  VS  Djurgardens 0 : 1/4\n08/09 1:00  Malmo  VS  AIK Fotboll 0 : 0</textarea><div class="actions"><button class="btn" onclick="preview()">⚙️ PROSES & BUAT PREDIKSI</button></div><div id="msg" style="font-size:12px;margin-top:8px"></div></section><section id="previewPanel" class="panel hidden"><h2 style="margin:0">Preview</h2><div class="tw"><table><thead><tr><th>Liga</th><th>Tanggal</th><th>Jam</th><th>Match</th><th>HDP</th><th>Favorit</th><th>Prediksi</th><th>Skor</th></tr></thead><tbody id="previewRows"></tbody></table></div><div class="actions"><button class="btn" onclick="publishAll()">✅ PUBLIKASIKAN SEMUA</button><button class="btn2" onclick="preview()">🎲 Acak Ulang</button></div></section><section class="panel"><div class="top"><div><h2 style="margin:0">Data Tersimpan</h2><div id="savedCount" style="font-size:12px"></div></div><button class="danger" onclick="clearAll()">Hapus Semua</button></div><div class="tw"><table><thead><tr><th>Liga</th><th>Tanggal</th><th>Jam</th><th>Match</th><th>HDP</th><th>Prediksi</th><th>Skor</th><th>Aksi</th></tr></thead><tbody id="savedRows"></tbody></table></div></section></main><script>
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let previewData=[];async function api(u,o={}){const r=await fetch(u,{headers:{'content-type':'application/json',...(o.headers||{})},...o});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Request gagal');return j}async function login(){try{await api('/api/login',{method:'POST',body:JSON.stringify({username:user.value,password:pass.value})});loginBox.classList.add('hidden');app.classList.remove('hidden');loadSaved()}catch(e){loginMsg.textContent=e.message}}async function logout(){await api('/api/logout',{method:'POST'});location.reload()}async function check(){try{const j=await api('/api/me');if(j.authenticated){loginBox.classList.add('hidden');app.classList.remove('hidden');loadSaved()}}catch{}}async function preview(){try{const j=await api('/api/parse',{method:'POST',body:JSON.stringify({raw:bulk.value,year:year.value})});previewData=j.matches||[];msg.textContent='Terbaca '+previewData.length+' pertandingan'+(j.errors?.length?' • '+j.errors.length+' baris gagal':'');previewPanel.classList.toggle('hidden',!previewData.length);previewRows.innerHTML=previewData.map(x=>'<tr><td>'+E(x.league)+'</td><td>'+E(x.date_display)+'</td><td>'+E(x.kickoff)+'</td><td><b>'+E(x.home)+'</b> vs <b>'+E(x.away)+'</b></td><td>'+E(x.handicap)+'</td><td>'+E(x.favorite)+'</td><td class="pick">'+E(x.prediction)+'</td><td><b>'+E(x.score)+'</b></td></tr>').join('')}catch(e){msg.textContent=e.message}}async function publishAll(){if(!previewData.length)return;await api('/api/matches/bulk',{method:'POST',body:JSON.stringify({matches:previewData})});alert(previewData.length+' pertandingan dipublikasikan.');previewData=[];previewPanel.classList.add('hidden');loadSaved()}async function loadSaved(){const j=await api('/api/matches');const d=j.matches||[];savedCount.textContent=d.length+' pertandingan tersimpan';savedRows.innerHTML=d.length?d.map(x=>'<tr><td>'+E(x.league)+'</td><td>'+E(x.date_display)+'</td><td>'+E(x.kickoff)+'</td><td><b>'+E(x.home)+'</b> vs <b>'+E(x.away)+'</b></td><td>'+E(x.handicap)+'</td><td class="pick">'+E(x.prediction)+'</td><td><b>'+E(x.score)+'</b></td><td><button class="danger" onclick="del('+x.id+')">Hapus</button></td></tr>').join(''):'<tr><td colspan="8">Belum ada data.</td></tr>'}async function del(id){if(confirm('Hapus pertandingan ini?')){await api('/api/matches/'+id,{method:'DELETE'});loadSaved()}}async function clearAll(){if(confirm('Hapus SEMUA pertandingan?')){await api('/api/matches',{method:'DELETE'});loadSaved()}}check();
</script></body></html>`;

async function api(req,env,url){const p=url.pathname;if(p==='/api/login'&&req.method==='POST'){const b=await req.json().catch(()=>({}));if(!eq(b.username,env.ADMIN_USERNAME)||!eq(b.password,env.ADMIN_PASSWORD))return J({error:'Username atau password salah.'},401);const t=await makeSession(env);return J({ok:true},200,{'set-cookie':`bp_session=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`})}if(p==='/api/logout'&&req.method==='POST')return J({ok:true},200,{'set-cookie':'bp_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});if(p==='/api/me')return J({authenticated:await admin(req,env)});if(p==='/api/matches'&&req.method==='GET'){const{results}=await env.DB.prepare('SELECT * FROM matches ORDER BY match_date,kickoff,id').all();return J({matches:results||[]})}if(p==='/api/parse'&&req.method==='POST'){if(!await admin(req,env))return J({error:'Login admin diperlukan.'},401);const b=await req.json().catch(()=>({}));return J(parseBulk(b.raw,String(b.year||new Date().getFullYear())))}if(p==='/api/matches/bulk'&&req.method==='POST'){if(!await admin(req,env))return J({error:'Login admin diperlukan.'},401);const b=await req.json().catch(()=>({})),ms=Array.isArray(b.matches)?b.matches:[];if(!ms.length)return J({error:'Tidak ada pertandingan.'},400);if(ms.length>300)return J({error:'Maksimal 300 pertandingan.'},400);await env.DB.batch(ms.map(x=>env.DB.prepare('INSERT INTO matches (league,match_date,date_display,kickoff,home,away,handicap,favorite,prediction,score) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(String(x.league||'').slice(0,120),String(x.match_date||'').slice(0,10),String(x.date_display||'').slice(0,10),String(x.kickoff||'').slice(0,5),String(x.home||'').slice(0,120),String(x.away||'').slice(0,120),String(x.handicap||'').slice(0,30),String(x.favorite||'').slice(0,120),String(x.prediction||'').slice(0,160),String(x.score||'').slice(0,20))));return J({ok:true,inserted:ms.length})}const m=p.match(/^\/api\/matches\/(\d+)$/);if(m&&req.method==='DELETE'){if(!await admin(req,env))return J({error:'Login admin diperlukan.'},401);await env.DB.prepare('DELETE FROM matches WHERE id=?').bind(Number(m[1])).run();return J({ok:true})}if(p==='/api/matches'&&req.method==='DELETE'){if(!await admin(req,env))return J({error:'Login admin diperlukan.'},401);await env.DB.prepare('DELETE FROM matches').run();return J({ok:true})}return J({error:'Not found'},404)}

export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname.startsWith('/api/'))return api(req,env,u);if(u.pathname==='/admin')return H(ADMIN);if(u.pathname==='/'||u.pathname==='/index.html')return H(PUBLIC);return H('<h1>404</h1>',404)}catch(e){return J({error:'Server error',detail:String(e?.message||e)},500)}}};
